; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115_200
upload_speed = 460_800
monitor_filters = time
lib_deps =
	gyverlibs/GyverNTC@^1.5.5
	gyverlibs/Settings@^1.3.13
	gyverlibs/GyverINA@^1.2.3
	gyverlibs/GSON@^1.8.4
	esphome/ESPAsyncWebServer-esphome@^3.3.0
	#git@github.com:bagrusss/GyverOLED.git#dev
	#git@github.com:bagrusss/INA_231.git#master
	https://github.com/bagrusss/GyverOLED.git#dev
	https://github.com/bagrusss/INA_231.git#master

extra_scripts = pre:scripts/generate_buildinfo.py

; Build data
version = 1.0.0
build_type = debug
build_number = 1

; ESP8266
[env:nodemcu]
platform = espressif8266
board = nodemcu
board_build.f_cpu = 80000000L
board_build.partitions = partitions_esp8266.csv
board_build.filesystem = littlefs

; ESP32
;[env:esp32_env]
;platform = espressif32
;board = esp32dev
;board_build.f_cpu = 240000000L
;board_build.partitions = partitions_esp32.csv
;board_build.filesystem = spiffs
;build_flags = ${env.build_flags} -Os -ffunction-sections -fdata-sections -Wl,--gc-sections -fno-exceptions -fno-rtti

;[env:nodemcu_app]
;extends = nodemcu
;platform = espressif8266
;board = nodemcu
;upload_command =
;  $UPLOADER $UPLOAD_FLAGS --chip esp8266 --port $UPLOAD_PORT --baud $UPLOAD_SPEED --before default_reset --after hard_reset write_flash 0x10000 $SOURCE

build_flags =
	-Wno-deprecated-declarations
	;-fno-exceptions
	;-frtti

build_unflags =
	;-fno-rtti

;build_type = debug


